server:
  port: 8081

spring:
  application:
    name: crm

  datasource:
    url: jdbc:mysql://localhost:3306/crmdb

    username: root

    driverClassName: com.mysql.cj.jdbc.Driver
    password: 892987

  jpa:
    #    database-platform: org.hibernate.dialect.MySQLDialect
    #    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 525884585511-bpgg7p3514v51ad4553fiqj5s7dem2dp.apps.googleusercontent.com # Replace with your actual Client ID
            client-secret: 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 # Replace with your actual Client Secret
            scope:
              - openid
              - profile
              - email
